;;; org-tag-beautify.el --- Beautify Org Mode tags. -*- lexical-binding: t; -*-
;; -*- coding: utf-8 -*-

;;; Time-stamp: <2021-01-09 13:38:05 stardiviner>

;; Authors: stardiviner <numbchild@gmail.com>
;; Package-Requires: ((emacs "26.1") (org-pretty-tags "0.2.2") (all-the-icons "4.0.0"))
;; Package-Version: 0.1.0
;; Keywords: hypermedia
;; homepage: https://github.com/stardiviner/org-tag-beautify

;; Copyright (C) 2020-2021 Free Software Foundation, Inc.
;; The source code is licensed under GPLv3.
;; The image data is NOT licensed under GPLv3.

;; org-tag-beautify is free software; you can redistribute it and/or modify it
;; under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.
;;
;; org-tag-beautify is distributed in the hope that it will be useful, but WITHOUT
;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
;; or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
;; License for more details.
;;
;;
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Usage:
;;
;; (org-tag-beautify-mode 1)

;;; Code:

(require 'org-pretty-tags)
(require 'all-the-icons)

(defgroup org-tag-beautify nil
  "Customize group of `org-tag-beautify-mode'."
  :prefix "org-tag-beautify-"
  :group 'org)


(defun org-tag-beautify-set-countries-tag-icons ()
  "Display countries name tag as flag icon."
  (let ((dir (concat (file-name-directory (or load-file-name (buffer-file-name)))
                     "data/countries/")))
    (setq org-pretty-tags-surrogate-strings
          (append org-pretty-tags-surrogate-strings
                  `(("afghanistan" . ,(create-image (concat dir "afghanistan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("aland_islands" . ,(create-image (concat dir "aland-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("albania" . ,(create-image (concat dir "albania.png") nil nil :ascent 'center :height 35 :width 35))
                    ("algeria" . ,(create-image (concat dir "algeria.png") nil nil :ascent 'center :height 35 :width 35))
                    ("american_samoa" . ,(create-image (concat dir "american-samoa.png") nil nil :ascent 'center :height 35 :width 35))
                    ("andorra" . ,(create-image (concat dir "andorra.png") nil nil :ascent 'center :height 35 :width 35))
                    ("angola" . ,(create-image (concat dir "angola.png") nil nil :ascent 'center :height 35 :width 35))
                    ("anguilla" . ,(create-image (concat dir "anguilla.png") nil nil :ascent 'center :height 35 :width 35))
                    ("antigua_and_barbuda" . ,(create-image (concat dir "antigua-and-barbuda.png") nil nil :ascent 'center :height 35 :width 35))
                    ("argentina" . ,(create-image (concat dir "argentina.png") nil nil :ascent 'center :height 35 :width 35))
                    ("armenia" . ,(create-image (concat dir "armenia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("aruba" . ,(create-image (concat dir "aruba.png") nil nil :ascent 'center :height 35 :width 35))
                    ("australia" . ,(create-image (concat dir "australia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("austria" . ,(create-image (concat dir "austria.png") nil nil :ascent 'center :height 35 :width 35))
                    ("azerbaijan" . ,(create-image (concat dir "azerbaijan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("azores_islands" . ,(create-image (concat dir "azores-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bahamas" . ,(create-image (concat dir "bahamas.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bahrain" . ,(create-image (concat dir "bahrain.png") nil nil :ascent 'center :height 35 :width 35))
                    ("balearic_islands" . ,(create-image (concat dir "balearic-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bangladesh" . ,(create-image (concat dir "bangladesh.png") nil nil :ascent 'center :height 35 :width 35))
                    ("barbados" . ,(create-image (concat dir "barbados.png") nil nil :ascent 'center :height 35 :width 35))
                    ("basque_country" . ,(create-image (concat dir "basque-country.png") nil nil :ascent 'center :height 35 :width 35))
                    ("belarus" . ,(create-image (concat dir "belarus.png") nil nil :ascent 'center :height 35 :width 35))
                    ("belgium" . ,(create-image (concat dir "belgium.png") nil nil :ascent 'center :height 35 :width 35))
                    ("belize" . ,(create-image (concat dir "belize.png") nil nil :ascent 'center :height 35 :width 35))
                    ("benin" . ,(create-image (concat dir "benin.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bermuda" . ,(create-image (concat dir "bermuda.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bhutan" . ,(create-image (concat dir "bhutan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bolivia" . ,(create-image (concat dir "bolivia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bonaire" . ,(create-image (concat dir "bonaire.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bosnia_and_herzegovina" . ,(create-image (concat dir "bosnia-and-herzegovina.png") nil nil :ascent 'center :height 35 :width 35))
                    ("botswana" . ,(create-image (concat dir "botswana.png") nil nil :ascent 'center :height 35 :width 35))
                    ("brazil" . ,(create-image (concat dir "brazil.png") nil nil :ascent 'center :height 35 :width 35))
                    ("british_columbia" . ,(create-image (concat dir "british-columbia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("british_indian_ocean_territory" . ,(create-image (concat dir "british-indian-ocean-territory.png") nil nil :ascent 'center :height 35 :width 35))
                    ("british_virgin_islands" . ,(create-image (concat dir "british-virgin-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("brunei" . ,(create-image (concat dir "brunei.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bulgaria" . ,(create-image (concat dir "bulgaria.png") nil nil :ascent 'center :height 35 :width 35))
                    ("burkina_faso" . ,(create-image (concat dir "burkina-faso.png") nil nil :ascent 'center :height 35 :width 35))
                    ("burundi" . ,(create-image (concat dir "burundi.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cambodia" . ,(create-image (concat dir "cambodia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cameroon" . ,(create-image (concat dir "cameroon.png") nil nil :ascent 'center :height 35 :width 35))
                    ("canada" . ,(create-image (concat dir "canada.png") nil nil :ascent 'center :height 35 :width 35))
                    ("canary_islands" . ,(create-image (concat dir "canary-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cape_verde" . ,(create-image (concat dir "cape-verde.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cayman_islands" . ,(create-image (concat dir "cayman-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("central_african_republic" . ,(create-image (concat dir "central-african-republic.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ceuta" . ,(create-image (concat dir "ceuta.png") nil nil :ascent 'center :height 35 :width 35))
                    ("chad" . ,(create-image (concat dir "chad.png") nil nil :ascent 'center :height 35 :width 35))
                    ("chile" . ,(create-image (concat dir "chile.png") nil nil :ascent 'center :height 35 :width 35))
                    ("china" . ,(create-image (concat dir "china.png") nil nil :ascent 'center :height 35 :width 35))
                    ("christmas_island" . ,(create-image (concat dir "christmas-island.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cocos_island" . ,(create-image (concat dir "cocos-island.png") nil nil :ascent 'center :height 35 :width 35))
                    ("colombia" . ,(create-image (concat dir "colombia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("comoros" . ,(create-image (concat dir "comoros.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cook_islands" . ,(create-image (concat dir "cook-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("corsica" . ,(create-image (concat dir "corsica.png") nil nil :ascent 'center :height 35 :width 35))
                    ("costa_rica" . ,(create-image (concat dir "costa-rica.png") nil nil :ascent 'center :height 35 :width 35))
                    ("croatia" . ,(create-image (concat dir "croatia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cuba" . ,(create-image (concat dir "cuba.png") nil nil :ascent 'center :height 35 :width 35))
                    ("curacao" . ,(create-image (concat dir "curacao.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cyprus" . ,(create-image (concat dir "cyprus.png") nil nil :ascent 'center :height 35 :width 35))
                    ("czech_republic" . ,(create-image (concat dir "czech-republic.png") nil nil :ascent 'center :height 35 :width 35))
                    ("democratic_republic_of_congo" . ,(create-image (concat dir "democratic-republic-of-congo.png") nil nil :ascent 'center :height 35 :width 35))
                    ("denmark" . ,(create-image (concat dir "denmark.png") nil nil :ascent 'center :height 35 :width 35))
                    ("djibouti" . ,(create-image (concat dir "djibouti.png") nil nil :ascent 'center :height 35 :width 35))
                    ("dominica" . ,(create-image (concat dir "dominica.png") nil nil :ascent 'center :height 35 :width 35))
                    ("dominican_republic" . ,(create-image (concat dir "dominican-republic.png") nil nil :ascent 'center :height 35 :width 35))
                    ("east_timor" . ,(create-image (concat dir "east-timor.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ecuador" . ,(create-image (concat dir "ecuador.png") nil nil :ascent 'center :height 35 :width 35))
                    ("egypt" . ,(create-image (concat dir "egypt.png") nil nil :ascent 'center :height 35 :width 35))
                    ("el_salvador" . ,(create-image (concat dir "el-salvador.png") nil nil :ascent 'center :height 35 :width 35))
                    ("england" . ,(create-image (concat dir "england.png") nil nil :ascent 'center :height 35 :width 35))
                    ("equatorial_guinea" . ,(create-image (concat dir "equatorial-guinea.png") nil nil :ascent 'center :height 35 :width 35))
                    ("eritrea" . ,(create-image (concat dir "eritrea.png") nil nil :ascent 'center :height 35 :width 35))
                    ("estonia" . ,(create-image (concat dir "estonia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ethiopia" . ,(create-image (concat dir "ethiopia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("european_union" . ,(create-image (concat dir "european-union.png") nil nil :ascent 'center :height 35 :width 35))
                    ("falkland_islands" . ,(create-image (concat dir "falkland-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("faroe_islands" . ,(create-image (concat dir "faroe-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("fiji" . ,(create-image (concat dir "fiji.png") nil nil :ascent 'center :height 35 :width 35))
                    ("finland" . ,(create-image (concat dir "finland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("france" . ,(create-image (concat dir "france.png") nil nil :ascent 'center :height 35 :width 35))
                    ("french_polynesia" . ,(create-image (concat dir "french-polynesia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("gabon" . ,(create-image (concat dir "gabon.png") nil nil :ascent 'center :height 35 :width 35))
                    ("galapagos_islands" . ,(create-image (concat dir "galapagos-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("gambia" . ,(create-image (concat dir "gambia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("georgia" . ,(create-image (concat dir "georgia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("germany" . ,(create-image (concat dir "germany.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ghana" . ,(create-image (concat dir "ghana.png") nil nil :ascent 'center :height 35 :width 35))
                    ("gibraltar" . ,(create-image (concat dir "gibraltar.png") nil nil :ascent 'center :height 35 :width 35))
                    ("greece" . ,(create-image (concat dir "greece.png") nil nil :ascent 'center :height 35 :width 35))
                    ("greenland" . ,(create-image (concat dir "greenland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("grenada" . ,(create-image (concat dir "grenada.png") nil nil :ascent 'center :height 35 :width 35))
                    ("guam" . ,(create-image (concat dir "guam.png") nil nil :ascent 'center :height 35 :width 35))
                    ("guatemala" . ,(create-image (concat dir "guatemala.png") nil nil :ascent 'center :height 35 :width 35))
                    ("guernsey" . ,(create-image (concat dir "guernsey.png") nil nil :ascent 'center :height 35 :width 35))
                    ("guinea_bissau" . ,(create-image (concat dir "guinea-bissau.png") nil nil :ascent 'center :height 35 :width 35))
                    ("guinea" . ,(create-image (concat dir "guinea.png") nil nil :ascent 'center :height 35 :width 35))
                    ("haiti" . ,(create-image (concat dir "haiti.png") nil nil :ascent 'center :height 35 :width 35))
                    ("hawaii" . ,(create-image (concat dir "hawaii.png") nil nil :ascent 'center :height 35 :width 35))
                    ("honduras" . ,(create-image (concat dir "honduras.png") nil nil :ascent 'center :height 35 :width 35))
                    ("hong_kong" . ,(create-image (concat dir "hong-kong.png") nil nil :ascent 'center :height 35 :width 35))
                    ("hungary" . ,(create-image (concat dir "hungary.png") nil nil :ascent 'center :height 35 :width 35))
                    ("iceland" . ,(create-image (concat dir "iceland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("india" . ,(create-image (concat dir "india.png") nil nil :ascent 'center :height 35 :width 35))
                    ("indonesia" . ,(create-image (concat dir "indonesia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("iran" . ,(create-image (concat dir "iran.png") nil nil :ascent 'center :height 35 :width 35))
                    ("iraq" . ,(create-image (concat dir "iraq.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ireland" . ,(create-image (concat dir "ireland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("isle_of_man" . ,(create-image (concat dir "isle-of-man.png") nil nil :ascent 'center :height 35 :width 35))
                    ("israel" . ,(create-image (concat dir "israel.png") nil nil :ascent 'center :height 35 :width 35))
                    ("italy" . ,(create-image (concat dir "italy.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ivory_coast" . ,(create-image (concat dir "ivory-coast.png") nil nil :ascent 'center :height 35 :width 35))
                    ("jamaica" . ,(create-image (concat dir "jamaica.png") nil nil :ascent 'center :height 35 :width 35))
                    ("japan" . ,(create-image (concat dir "japan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("jersey" . ,(create-image (concat dir "jersey.png") nil nil :ascent 'center :height 35 :width 35))
                    ("jordan" . ,(create-image (concat dir "jordan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("kazakhstan" . ,(create-image (concat dir "kazakhstan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("kenya" . ,(create-image (concat dir "kenya.png") nil nil :ascent 'center :height 35 :width 35))
                    ("kiribati" . ,(create-image (concat dir "kiribati.png") nil nil :ascent 'center :height 35 :width 35))
                    ("kosovo" . ,(create-image (concat dir "kosovo.png") nil nil :ascent 'center :height 35 :width 35))
                    ("kuwait" . ,(create-image (concat dir "kuwait.png") nil nil :ascent 'center :height 35 :width 35))
                    ("kyrgyzstan" . ,(create-image (concat dir "kyrgyzstan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("laos" . ,(create-image (concat dir "laos.png") nil nil :ascent 'center :height 35 :width 35))
                    ("latvia" . ,(create-image (concat dir "latvia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("lebanon" . ,(create-image (concat dir "lebanon.png") nil nil :ascent 'center :height 35 :width 35))
                    ("lesotho" . ,(create-image (concat dir "lesotho.png") nil nil :ascent 'center :height 35 :width 35))
                    ("liberia" . ,(create-image (concat dir "liberia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("libya" . ,(create-image (concat dir "libya.png") nil nil :ascent 'center :height 35 :width 35))
                    ("liechtenstein" . ,(create-image (concat dir "liechtenstein.png") nil nil :ascent 'center :height 35 :width 35))
                    ("lithuania" . ,(create-image (concat dir "lithuania.png") nil nil :ascent 'center :height 35 :width 35))
                    ("luxembourg" . ,(create-image (concat dir "luxembourg.png") nil nil :ascent 'center :height 35 :width 35))
                    ("macao" . ,(create-image (concat dir "macao.png") nil nil :ascent 'center :height 35 :width 35))
                    ("madagascar" . ,(create-image (concat dir "madagascar.png") nil nil :ascent 'center :height 35 :width 35))
                    ("madeira" . ,(create-image (concat dir "madeira.png") nil nil :ascent 'center :height 35 :width 35))
                    ("malawi" . ,(create-image (concat dir "malawi.png") nil nil :ascent 'center :height 35 :width 35))
                    ("malaysia" . ,(create-image (concat dir "malaysia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("maldives" . ,(create-image (concat dir "maldives.png") nil nil :ascent 'center :height 35 :width 35))
                    ("mali" . ,(create-image (concat dir "mali.png") nil nil :ascent 'center :height 35 :width 35))
                    ("malta" . ,(create-image (concat dir "malta.png") nil nil :ascent 'center :height 35 :width 35))
                    ("marshall_island" . ,(create-image (concat dir "marshall-island.png") nil nil :ascent 'center :height 35 :width 35))
                    ("martinique" . ,(create-image (concat dir "martinique.png") nil nil :ascent 'center :height 35 :width 35))
                    ("mauritania" . ,(create-image (concat dir "mauritania.png") nil nil :ascent 'center :height 35 :width 35))
                    ("mauritius" . ,(create-image (concat dir "mauritius.png") nil nil :ascent 'center :height 35 :width 35))
                    ("melilla" . ,(create-image (concat dir "melilla.png") nil nil :ascent 'center :height 35 :width 35))
                    ("mexico" . ,(create-image (concat dir "mexico.png") nil nil :ascent 'center :height 35 :width 35))
                    ("micronesia" . ,(create-image (concat dir "micronesia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("moldova" . ,(create-image (concat dir "moldova.png") nil nil :ascent 'center :height 35 :width 35))
                    ("monaco" . ,(create-image (concat dir "monaco.png") nil nil :ascent 'center :height 35 :width 35))
                    ("mongolia" . ,(create-image (concat dir "mongolia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("montenegro" . ,(create-image (concat dir "montenegro.png") nil nil :ascent 'center :height 35 :width 35))
                    ("montserrat" . ,(create-image (concat dir "montserrat.png") nil nil :ascent 'center :height 35 :width 35))
                    ("morocco" . ,(create-image (concat dir "morocco.png") nil nil :ascent 'center :height 35 :width 35))
                    ("mozambique" . ,(create-image (concat dir "mozambique.png") nil nil :ascent 'center :height 35 :width 35))
                    ("myanmar" . ,(create-image (concat dir "myanmar.png") nil nil :ascent 'center :height 35 :width 35))
                    ("namibia" . ,(create-image (concat dir "namibia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("nauru" . ,(create-image (concat dir "nauru.png") nil nil :ascent 'center :height 35 :width 35))
                    ("nepal" . ,(create-image (concat dir "nepal.png") nil nil :ascent 'center :height 35 :width 35))
                    ("netherlands" . ,(create-image (concat dir "netherlands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("new_zealand" . ,(create-image (concat dir "new-zealand.png") nil nil :ascent 'center :height 35 :width 35))
                    ("nicaragua" . ,(create-image (concat dir "nicaragua.png") nil nil :ascent 'center :height 35 :width 35))
                    ("niger" . ,(create-image (concat dir "niger.png") nil nil :ascent 'center :height 35 :width 35))
                    ("nigeria" . ,(create-image (concat dir "nigeria.png") nil nil :ascent 'center :height 35 :width 35))
                    ("niue" . ,(create-image (concat dir "niue.png") nil nil :ascent 'center :height 35 :width 35))
                    ("norfolk_island" . ,(create-image (concat dir "norfolk-island.png") nil nil :ascent 'center :height 35 :width 35))
                    ("north_korea" . ,(create-image (concat dir "north-korea.png") nil nil :ascent 'center :height 35 :width 35))
                    ("northen_cyprus" . ,(create-image (concat dir "northen-cyprus.png") nil nil :ascent 'center :height 35 :width 35))
                    ("northern_marianas_islands" . ,(create-image (concat dir "northern-marianas-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("norway" . ,(create-image (concat dir "norway.png") nil nil :ascent 'center :height 35 :width 35))
                    ("oman" . ,(create-image (concat dir "oman.png") nil nil :ascent 'center :height 35 :width 35))
                    ("orkney_islands" . ,(create-image (concat dir "orkney-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ossetia" . ,(create-image (concat dir "ossetia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("otan" . ,(create-image (concat dir "otan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("pakistan" . ,(create-image (concat dir "pakistan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("palau" . ,(create-image (concat dir "palau.png") nil nil :ascent 'center :height 35 :width 35))
                    ("palestine" . ,(create-image (concat dir "palestine.png") nil nil :ascent 'center :height 35 :width 35))
                    ("panama" . ,(create-image (concat dir "panama.png") nil nil :ascent 'center :height 35 :width 35))
                    ("papua_new_guinea" . ,(create-image (concat dir "papua-new-guinea.png") nil nil :ascent 'center :height 35 :width 35))
                    ("peru" . ,(create-image (concat dir "peru.png") nil nil :ascent 'center :height 35 :width 35))
                    ("philippines" . ,(create-image (concat dir "philippines.png") nil nil :ascent 'center :height 35 :width 35))
                    ("pitcairn_islands" . ,(create-image (concat dir "pitcairn-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("poland" . ,(create-image (concat dir "poland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("portugal" . ,(create-image (concat dir "portugal.png") nil nil :ascent 'center :height 35 :width 35))
                    ("puerto_rico" . ,(create-image (concat dir "puerto-rico.png") nil nil :ascent 'center :height 35 :width 35))
                    ("qatar" . ,(create-image (concat dir "qatar.png") nil nil :ascent 'center :height 35 :width 35))
                    ("rapa_nui" . ,(create-image (concat dir "rapa-nui.png") nil nil :ascent 'center :height 35 :width 35))
                    ("republic_of_macedonia" . ,(create-image (concat dir "republic-of-macedonia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("republic_of_the_congo" . ,(create-image (concat dir "republic-of-the-congo.png") nil nil :ascent 'center :height 35 :width 35))
                    ("romania" . ,(create-image (concat dir "romania.png") nil nil :ascent 'center :height 35 :width 35))
                    ("russia" . ,(create-image (concat dir "russia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("rwanda" . ,(create-image (concat dir "rwanda.png") nil nil :ascent 'center :height 35 :width 35))
                    ("saba_island" . ,(create-image (concat dir "saba-island.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sahrawi_arab_democratic_republic" . ,(create-image (concat dir "sahrawi-arab-democratic-republic.png") nil nil :ascent 'center :height 35 :width 35))
                    ("saint_kitts_and_nevis" . ,(create-image (concat dir "saint-kitts-and-nevis.png") nil nil :ascent 'center :height 35 :width 35))
                    ("samoa" . ,(create-image (concat dir "samoa.png") nil nil :ascent 'center :height 35 :width 35))
                    ("san_marino" . ,(create-image (concat dir "san-marino.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sao_tome_and_principe" . ,(create-image (concat dir "sao-tome-and-principe.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sardinia" . ,(create-image (concat dir "sardinia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("saudi_arabia" . ,(create-image (concat dir "saudi-arabia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("scotland" . ,(create-image (concat dir "scotland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("senegal" . ,(create-image (concat dir "senegal.png") nil nil :ascent 'center :height 35 :width 35))
                    ("serbia" . ,(create-image (concat dir "serbia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("seychelles" . ,(create-image (concat dir "seychelles.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sicily" . ,(create-image (concat dir "sicily.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sierra_leone" . ,(create-image (concat dir "sierra-leone.png") nil nil :ascent 'center :height 35 :width 35))
                    ("singapore" . ,(create-image (concat dir "singapore.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sint_eustatius" . ,(create-image (concat dir "sint-eustatius.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sint_maarten" . ,(create-image (concat dir "sint-maarten.png") nil nil :ascent 'center :height 35 :width 35))
                    ("slovakia" . ,(create-image (concat dir "slovakia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("slovenia" . ,(create-image (concat dir "slovenia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("solomon_islands" . ,(create-image (concat dir "solomon-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("somalia" . ,(create-image (concat dir "somalia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("somaliland" . ,(create-image (concat dir "somaliland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("south_africa" . ,(create-image (concat dir "south-africa.png") nil nil :ascent 'center :height 35 :width 35))
                    ("south_korea" . ,(create-image (concat dir "south-korea.png") nil nil :ascent 'center :height 35 :width 35))
                    ("south_sudan" . ,(create-image (concat dir "south-sudan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("spain" . ,(create-image (concat dir "spain.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sri_lanka" . ,(create-image (concat dir "sri-lanka.png") nil nil :ascent 'center :height 35 :width 35))
                    ("st_barts" . ,(create-image (concat dir "st-barts.png") nil nil :ascent 'center :height 35 :width 35))
                    ("st_lucia" . ,(create-image (concat dir "st-lucia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("st_vincent_and_the_grenadines" . ,(create-image (concat dir "st-vincent-and-the-grenadines.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sudan" . ,(create-image (concat dir "sudan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("suriname" . ,(create-image (concat dir "suriname.png") nil nil :ascent 'center :height 35 :width 35))
                    ("swaziland" . ,(create-image (concat dir "swaziland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sweden" . ,(create-image (concat dir "sweden.png") nil nil :ascent 'center :height 35 :width 35))
                    ("switzerland" . ,(create-image (concat dir "switzerland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("syria" . ,(create-image (concat dir "syria.png") nil nil :ascent 'center :height 35 :width 35))
                    ("taiwan" . ,(create-image (concat dir "taiwan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tajikistan" . ,(create-image (concat dir "tajikistan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tanzania" . ,(create-image (concat dir "tanzania.png") nil nil :ascent 'center :height 35 :width 35))
                    ("thailand" . ,(create-image (concat dir "thailand.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tibet" . ,(create-image (concat dir "tibet.png") nil nil :ascent 'center :height 35 :width 35))
                    ("togo" . ,(create-image (concat dir "togo.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tokelau" . ,(create-image (concat dir "tokelau.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tonga" . ,(create-image (concat dir "tonga.png") nil nil :ascent 'center :height 35 :width 35))
                    ("transnistria" . ,(create-image (concat dir "transnistria.png") nil nil :ascent 'center :height 35 :width 35))
                    ("trinidad_and_tobago" . ,(create-image (concat dir "trinidad-and-tobago.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tubalu" . ,(create-image (concat dir "tubalu.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tunisia" . ,(create-image (concat dir "tunisia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("turkey" . ,(create-image (concat dir "turkey.png") nil nil :ascent 'center :height 35 :width 35))
                    ("turkmenistan" . ,(create-image (concat dir "turkmenistan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("turks_and_caicos" . ,(create-image (concat dir "turks-and-caicos.png") nil nil :ascent 'center :height 35 :width 35))
                    ("uganda" . ,(create-image (concat dir "uganda.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ukraine" . ,(create-image (concat dir "ukraine.png") nil nil :ascent 'center :height 35 :width 35))
                    ("united_arab_emirates" . ,(create-image (concat dir "united-arab-emirates.png") nil nil :ascent 'center :height 35 :width 35))
                    ("united_kingdom" . ,(create-image (concat dir "united-kingdom.png") nil nil :ascent 'center :height 35 :width 35))
                    ("united_nations" . ,(create-image (concat dir "united-nations.png") nil nil :ascent 'center :height 35 :width 35))
                    ("america" . ,(create-image (concat dir "united-states-of-america.png") nil nil :ascent 'center :height 35 :width 35))
                    ("uruguay" . ,(create-image (concat dir "uruguay.png") nil nil :ascent 'center :height 35 :width 35))
                    ("uzbekistn" . ,(create-image (concat dir "uzbekistn.png") nil nil :ascent 'center :height 35 :width 35))
                    ("vanuatu" . ,(create-image (concat dir "vanuatu.png") nil nil :ascent 'center :height 35 :width 35))
                    ("vatican_city" . ,(create-image (concat dir "vatican-city.png") nil nil :ascent 'center :height 35 :width 35))
                    ("venezuela" . ,(create-image (concat dir "venezuela.png") nil nil :ascent 'center :height 35 :width 35))
                    ("vietnam" . ,(create-image (concat dir "vietnam.png") nil nil :ascent 'center :height 35 :width 35))
                    ("virgin_islands" . ,(create-image (concat dir "virgin-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("singapore" . ,(create-image (concat dir "singapore.png") nil nil :ascent 'center :height 35 :width 35))
                    ("yemen" . ,(create-image (concat dir "yemen.png") nil nil :ascent 'center :height 35 :width 35))
                    ("zambia" . ,(create-image (concat dir "zambia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("zimbabwe" . ,(create-image (concat dir "zimbabwe.png") nil nil :ascent 'center :height 35 :width 35)))))))

;;;###autoload
(defun org-tag-beautify-enable ()
  "Enable `org-tag-beautify'."
  (org-tag-beautify-set-countries-tag-icons))

;;;###autoload
(defun org-tag-beautify-disable ()
  "Disable `org-tag-beautify'."
  )

;;;###autoload
(define-minor-mode org-tag-beautify-mode
  "A minor mode that beautify Org tags with icons and images."
  :init-value nil
  :lighter nil
  :group 'org-tag-beautify
  :global t
  (if org-tag-beautify-mode
      (org-tag-beautify-enable)
    (org-tag-beautify-disable)))



(provide 'org-tag-beautify)

;;; org-tag-beautify.el ends here
